name: Pip.Services TestDelivery Nodex

# Cofigure trigger rules
on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  # Setup job
  setup:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Pull delivery scripts
      shell: bash
      run: |
        rm -rf script-delivery-py
        git clone ${{ secrets.SCRIPTS_DELIVERY_PY_GIT_URL }} script-delivery-py

    - name: Execute increment script
      shell: bash
      run: ./script-delivery-py/setup/increment/increment.py

    - name: Execute prerequisites script
      shell: bash
      run: ./script-delivery-py/setup/prereqs/prereqs.py

    - name: Cache delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

  # Authoring job
  authoring:
    needs: setup
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Get cached delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Execute build script
      shell: bash
      run: script-delivery-py/authoring/build/build.py

    - name: Execute test script
      shell: bash
      run: ./script-delivery-py/authoring/test/test.py

    - name: Execute package script
      shell: bash
      run: ./script-delivery-py/authoring/package/package.py

    - name: Execute publish script
      shell: bash
      run: ./script-delivery-py/authoring/publish/publish.py

    - name: Execute tag script
      shell: bash
      run: ./script-delivery-py/authoring/tag/tag.py

    - name: Execute clean script
      if: always()
      shell: bash
      run: ./script-delivery-py/authoring/clean/clean.py

  # Integration job
  integration:
    needs: authoring
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Get cached delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Execute prepare script
      shell: bash
      run: ./script-delivery-py/integration/prepare/prepare.py

    - name: Execute deploy script
      shell: bash
      run: ./script-delivery-py/integration/deploy/deploy.py

    - name: Execute ci_test script
      shell: bash
      run: ./script-delivery-py/integration/ci_test/ci_test.py

    - name: Execute rollback script
      shell: bash
      run: ./script-delivery-py/integration/rollback/rollback.py

  # Assembling job
  assembling:
    needs: integration
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Get cached delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Execute baseline script
      shell: bash
      run: ./script-delivery-py/assembling/baseline/baseline.py

    - name: Execute package_assembly script
      shell: bash
      run: ./script-delivery-py/assembling/package_assembly/package_assembly.py

    - name: Execute publish_assembly script
      shell: bash
      run: ./script-delivery-py/assembling/publish_assembly/publish_assembly.py

  # Acceptance job
  acceptance:
    needs: assembling
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Get cached delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Execute functional script
      shell: bash
      run: ./script-delivery-py/acceptance/functional/functional.py

    - name: Execute functional script
      shell: bash
      run: ./script-delivery-py/acceptance/benchmark/benchmark.py

    - name: Execute certify script
      shell: bash
      run: ./script-delivery-py/acceptance/certify/certify.py

  # Release job
  release:
    needs: acceptance
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Get cached delivery artifacts
      uses: actions/cache@v3
      with:
        path: |
          script-delivery-py
          component*.json
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Execute document script
      shell: bash
      run: ./script-delivery-py/release/document/document.py

    - name: Execute release script
      shell: bash
      run: ./script-delivery-py/release/release/release.py

    - name: Execute notify script
      shell: bash
      run: ./script-delivery-py/release/notify/notify.py

  # Measure job
  measure:
    needs: release
    if: always()
    runs-on: ubuntu-18.04

    steps: 
    - name: Get cached delivery artifact
      uses: actions/cache@v3
      with:
        path: script-delivery-py
        key: delivery-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Run script to get metrics and update s3 file
      env:
        name: $(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
      run: ./script-delivery-py/measure/measure.py ${{ github.repository_owner }} ${{ env.name }} ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.AWS_S3_BUCKET }} ${{ secrets.GITHUB_TOKEN }}
      shell: bash
